name: barbell
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  intl: ^0.20.2
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  persistent_bottom_nav_bar: ^6.2.1
  pinput: ^5.0.1
  slide_countdown: ^2.0.2
  image_picker: ^1.1.2
  permission_handler: ^12.0.0
  mobile_scanner: ^7.0.1
  slide_to_act: ^2.0.2
  linear_progress_bar: ^1.2.0
  swipeable_button_view: ^0.0.2
  syncfusion_flutter_gauges: ^30.1.37
  draggable_widget: ^2.0.0
  carousel_slider: ^5.0.0
  modal_bottom_sheet: ^3.0.0
  numberpicker: ^2.1.2
  vibration: ^3.1.3
  iconsax: ^0.0.8
  get: ^4.7.2
  web_socket_channel: ^3.0.1
  json_annotation: ^4.9.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  flutter_svg: ^2.2.0
  video_player: ^2.8.3
  youtube_player_flutter: ^9.1.1
  fl_chart: ^1.0.0
  fluttertoast: ^8.2.12
  dart_jsonwebtoken: ^3.2.0
  firebase_core: ^3.13.1
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.4
  shimmer: ^3.0.0
  flutter_slidable: ^4.0.0
  cached_network_image: ^3.4.1
  camera: ^0.10.6
  flutter_launcher_icons: ^0.14.4
  video_compress: ^3.1.2
  path_provider: ^2.1.4
  dio: ^5.8.0+1
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  http_parser: ^4.1.2
  flutter_html: ^3.0.0-beta.4
  flutter_quill: ^11.4.1
  flutter_keyboard_visibility: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_build_uploader: ^0.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
  

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
